name       : linux-tools
version    : 4.9.137
release    : 58
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.137.tar.xz : 6db2512a9094bf4c830124641d1275635600b052962a7db3556da18914ea2589
license    : GPL-2.0-only
component  :
    - programming.tools
    - cpupower : programming.library
    - cpupower-devel : programming.devel
    - turbostat : system.utils
    - x86_energy_perf_policy : system.utils
summary    :
    - Useful kernel development tools such as perf
    - cpupower : The cpupower program
    - cpupower-devel : Development files for linux-tools-cpupower
    - turbostat : Reports on processor topology, frequency, idle power-state statistics,
        temperature, and power usage on Intel processors.
    - x86_energy_perf_policy : Allows programs and admins to define the relative importance
        of performance and energy efficiency.
libsplit   : no
description: |
    Useful kernel development tools such as 'perf'
patterns   :
    - cpupower :
        - /usr/bin/cpu*
        - /usr/sbin/cpu*
        - /usr/lib64/libcpu*.so.*
        - /usr/share/locale
        - /usr/share/man/man1/cpu*
    - cpupower-devel :
        - /usr/include/cpu*.h
        - /usr/lib64/libcpu*.so
    - turbostat :
        - /usr/bin/turbostat
        - /usr/share/man/man8/turbostat.8
    - x86_energy_perf_policy :
        - /usr/bin/x86_energy_perf_policy
        - /usr/share/man/man8/x86_energy_perf_policy.8
replaces   :
    - kernel-tools
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpci)
    - pkgconfig(libunwind)
    - pkgconfig(slang)
    - elfutils-devel
    - libelf-devel
    - perl
build      : |
    %make -C tools/perf WERROR=0 prefix=/usr
    %make -C tools/power/cpupower prefix=/usr
    %make -C tools/power/x86/x86_energy_perf_policy prefix=/usr
    %make -C tools/power/x86/turbostat prefix=/usr
install    : |
    mkdir -p $installdir/usr/share/man/man8/
    %make_install -C tools/perf WERROR=0 prefix=/usr
    %make_install -C tools/power/cpupower prefix=/usr mandir=/usr/share/man docdir=/usr/share/doc/${package} libdir=%libdir%
    install -D -m 00644 $installdir/etc/bash_completion.d/perf $installdir/usr/share/bash-completion/completions/perf

    %make_install -C tools/power/cpupower prefix=/usr mandir=/usr/share/man docdir=/usr/share/doc/${package} libdir=%libdir%

    %make_install -C tools/power/x86/turbostat prefix=/usr man8dir=/usr/share/man

    %make_install -C tools/power/x86/x86_energy_perf_policy prefix=/usr man8dir=/usr/share/man

    rm -rf $installdir/etc
