name       : linux-tools
version    : 4.9.21
release    : 7
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.9.21.tar.xz : 97503749bf7997b3e55a5126080df348e74c0bb0e10ad85b1b2ec9db7e5e6c24
license    : GPL-2.0
component  :
    - programming.tools
    - cpupower : programming.library
    - cpupower-devel : programming.devel
summary    :
    - Useful kernel development tools such as perf
    - cpupower : The cpupower program
    - cpupower-devel : Development files for linux-tools-cpupower
libsplit   : no
description: |
    Useful kernel development tools such as 'perf'
patterns   :
    - cpupower :
        - /usr/bin/cpu*
        - /usr/sbin/cpu*
        - /usr/lib64/libcpu*.so.*
        - /usr/share/locale
        - /usr/share/man/man1/cpu*
    - cpupower-devel :
        - /usr/include/cpu*.h
        - /usr/lib64/libcpu*.so
replaces   :
    - kernel-tools
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpci)
    - pkgconfig(libunwind)
    - pkgconfig(slang)
    - elfutils-devel
    - libelf-devel
    - perl
build      : |
    %make -C tools/perf WERROR=0 prefix=/usr
    %make -C tools/power/cpupower prefix=/usr
install    : |
    %make_install -C tools/perf WERROR=0 prefix=/usr
    %make_install -C tools/power/cpupower prefix=/usr mandir=/usr/share/man docdir=/usr/share/doc/${package} libdir=%libdir%
    install -D -m 00644 $installdir/etc/bash_completion.d/perf $installdir/usr/share/bash-completion/completions/perf
    rm -rf $installdir/etc
